// ─── Mock data for prototype mode ────────────────────────────────

export const mockUsers = {
  tenant: {
    id: "t1",
    email: "tenant@demo.com",
    full_name: "Amina Juma",
    role: "tenant",
    phone: "+255 712 345 678",
  },
  landlord: {
    id: "l1",
    email: "landlord@demo.com",
    full_name: "Hassan Mwangi",
    role: "landlord",
    phone: "+255 713 456 789",
  },
  admin: {
    id: "a1",
    email: "admin@demo.com",
    full_name: "Admin User",
    role: "admin",
    phone: "+255 714 567 890",
  },
};

export const mockProperties = [
  {
    id: "p1",
    title: "Studio ya Kisasa Masaki",
    description: "Studio nzuri ya kisasa yenye samani za hali ya juu, bafuni ya ndani, na mandhari ya bahari. Iko katika eneo tulivu la Masaki karibu na maduka na mikahawa.",
    price: 800000,
    location: "Masaki, Dar es Salaam",
    bedrooms: 1,
    property_type: "studio",
    amenities: ["WiFi", "Parking", "AC", "Ulinzi 24/7"],
    house_rules: ["Hakuna wanyama", "Hakuna kuvuta sigara"],
    images: ["/placeholder.svg"],
    listing_status: "published",
    verification_status: "verified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2025-12-01T10:00:00Z",
  },
  {
    id: "p2",
    title: "Nyumba 2BR Mikocheni",
    description: "Nyumba pana ya vyumba viwili vya kulala yenye sebule kubwa, jiko la kisasa, na balcony. Eneo la Mikocheni liko karibu na shule na hospitali.",
    price: 1200000,
    location: "Mikocheni, Dar es Salaam",
    bedrooms: 2,
    property_type: "apartment",
    amenities: ["WiFi", "Ulinzi", "Maji ya bomba", "Parking"],
    house_rules: ["Hakuna kelele baada ya 10PM"],
    images: ["/placeholder.svg"],
    listing_status: "published",
    verification_status: "verified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2025-11-15T08:00:00Z",
  },
  {
    id: "p3",
    title: "Chumba Sinza",
    description: "Chumba kimoja kizuri kwa bei nafuu na starehe. Karibu na daladala na maduka.",
    price: 500000,
    location: "Sinza, Dar es Salaam",
    bedrooms: 1,
    property_type: "apartment",
    amenities: ["Maji ya bomba"],
    house_rules: [],
    images: ["/placeholder.svg"],
    listing_status: "published",
    verification_status: "verified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2025-10-20T12:00:00Z",
  },
  {
    id: "p4",
    title: "Nyumba ya Familia Mbezi",
    description: "Nyumba kubwa ya familia yenye bustani, vyumba 3 vya kulala, na eneo la kucheza watoto.",
    price: 2000000,
    location: "Mbezi Beach",
    bedrooms: 3,
    property_type: "house",
    amenities: ["Bustani", "Parking", "WiFi", "Ulinzi"],
    house_rules: ["Wanyama wanaruhusiwa"],
    images: ["/placeholder.svg"],
    listing_status: "published",
    verification_status: "verified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2025-09-05T09:00:00Z",
  },
  {
    id: "p5",
    title: "Penthouse Oyster Bay",
    description: "Penthouse ya kifahari yenye bwawa la kuogelea, gym, na mandhari nzuri ya jiji.",
    price: 3500000,
    location: "Oyster Bay",
    bedrooms: 3,
    property_type: "apartment",
    amenities: ["Bwawa", "Gym", "WiFi", "Elevator", "AC"],
    house_rules: ["Hakuna sherehe"],
    images: ["/placeholder.svg"],
    listing_status: "published",
    verification_status: "verified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2025-08-10T14:00:00Z",
  },
  {
    id: "p6",
    title: "Chumba Kinondoni (Rasimu)",
    description: "Chumba kimoja bei nafuu.",
    price: 250000,
    location: "Kinondoni",
    bedrooms: 1,
    property_type: "room",
    amenities: [],
    house_rules: [],
    images: ["/placeholder.svg"],
    listing_status: "draft",
    verification_status: "unverified",
    owner: "l1",
    owner_name: "Hassan Mwangi",
    created_at: "2026-01-01T10:00:00Z",
  },
];

export const mockApplications = [
  {
    id: "app1",
    property: "p1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    tenant_email: "tenant@demo.com",
    tenant_phone: "+255 712 345 678",
    message: "Napenda sana nyumba hii, naomba kukodisha.",
    status: "approved",
    created_at: "2026-01-05T10:00:00Z",
  },
  {
    id: "app2",
    property: "p2",
    property_title: "Nyumba 2BR Mikocheni",
    tenant: "t1",
    tenant_name: "Amina Juma",
    tenant_email: "tenant@demo.com",
    tenant_phone: "+255 712 345 678",
    message: "Ninahitaji nyumba ya vyumba viwili kwa familia yangu.",
    status: "pending",
    created_at: "2026-01-10T14:00:00Z",
  },
];

export const mockViewings = [
  {
    id: "v1",
    application: "app1",
    property: "p1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    scheduled_date: "2026-01-15T09:00:00Z",
    time_window: "morning",
    status: "approved",
    created_at: "2026-01-06T08:00:00Z",
  },
];

export const mockOffers = [
  {
    id: "o1",
    application: "app1",
    viewing: "v1",
    property: "p1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    landlord: "l1",
    landlord_name: "Hassan Mwangi",
    monthly_rent: 800000,
    security_deposit: 800000,
    start_date: "2026-02-01",
    end_date: "2027-01-31",
    status: "pending",
    landlord_note: "Karibu sana!",
    created_at: "2026-01-16T10:00:00Z",
  },
];

export const mockLeases = [
  {
    id: "lease1",
    property: "p1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    landlord: "l1",
    landlord_name: "Hassan Mwangi",
    monthly_rent: 800000,
    security_deposit: 800000,
    start_date: "2026-02-01",
    end_date: "2027-01-31",
    status: "draft",
    house_rules: ["Hakuna wanyama", "Hakuna kuvuta sigara"],
    special_conditions: "Kodi ya kwanza ndani ya siku 7.",
    signed_at: null,
    created_at: "2026-01-20T10:00:00Z",
  },
];

export const mockInvoices = [
  {
    id: "inv1",
    lease: "lease1",
    property_title: "Studio ya Kisasa Masaki",
    tenant_name: "Amina Juma",
    amount: 800000,
    due_date: "2026-02-01",
    status: "unpaid",
    created_at: "2026-01-25T10:00:00Z",
  },
  {
    id: "inv2",
    lease: "lease1",
    property_title: "Studio ya Kisasa Masaki",
    tenant_name: "Amina Juma",
    amount: 800000,
    due_date: "2026-03-01",
    status: "paid",
    paid_at: "2026-02-28T10:00:00Z",
    created_at: "2026-02-01T10:00:00Z",
  },
];

export const mockPayments = [
  {
    id: "pay1",
    invoice: "inv2",
    property: "p1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    amount: 800000,
    method: "MOBILE",
    reference: "MPESA-123456",
    status: "confirmed",
    created_at: "2026-02-28T10:00:00Z",
  },
];

export const mockConversations = [
  {
    id: "conv1",
    application: "app1",
    property_title: "Studio ya Kisasa Masaki",
    tenant: "t1",
    tenant_name: "Amina Juma",
    landlord: "l1",
    landlord_name: "Hassan Mwangi",
    last_message: "Karibu, lini ungependa kuhamia?",
    updated_at: "2026-01-17T10:00:00Z",
  },
];

export const mockMessages = [
  {
    id: "msg1",
    conversation: "conv1",
    sender: "l1",
    sender_name: "Hassan Mwangi",
    content: "Habari! Ombi lako limekubaliwa. Karibu kuona nyumba.",
    created_at: "2026-01-06T10:00:00Z",
  },
  {
    id: "msg2",
    conversation: "conv1",
    sender: "t1",
    sender_name: "Amina Juma",
    content: "Asante sana! Nitakuja Jumatatu asubuhi.",
    created_at: "2026-01-06T11:00:00Z",
  },
  {
    id: "msg3",
    conversation: "conv1",
    sender: "l1",
    sender_name: "Hassan Mwangi",
    content: "Karibu, lini ungependa kuhamia?",
    created_at: "2026-01-17T10:00:00Z",
  },
];

export const mockAuditLogs = [
  { id: "log1", action: "application.created", entity_type: "application", entity_id: "app1", user_name: "Amina Juma", created_at: "2026-01-05T10:00:00Z", details: "Applied to Studio ya Kisasa Masaki" },
  { id: "log2", action: "application.approved", entity_type: "application", entity_id: "app1", user_name: "Hassan Mwangi", created_at: "2026-01-05T12:00:00Z", details: "Approved application" },
  { id: "log3", action: "viewing.created", entity_type: "viewing", entity_id: "v1", user_name: "Amina Juma", created_at: "2026-01-06T08:00:00Z", details: "Requested viewing for Studio ya Kisasa Masaki" },
  { id: "log4", action: "viewing.approved", entity_type: "viewing", entity_id: "v1", user_name: "Hassan Mwangi", created_at: "2026-01-06T09:00:00Z", details: "Approved viewing request" },
  { id: "log5", action: "offer.created", entity_type: "offer", entity_id: "o1", user_name: "Hassan Mwangi", created_at: "2026-01-16T10:00:00Z", details: "Created rental offer for Studio ya Kisasa Masaki" },
];

export const mockDashboardStats = {
  tenant: {
    total_applications: 2,
    approved_applications: 1,
    pending_viewings: 0,
    active_leases: 0,
    total_payments: 1,
  },
  landlord: {
    total_properties: 6,
    published_properties: 5,
    total_applications: 2,
    pending_applications: 1,
    active_leases: 0,
    total_revenue: 800000,
  },
  admin: {
    total_users: 3,
    total_properties: 6,
    pending_reviews: 1,
    total_payments: 1,
    active_disputes: 0,
  },
};
